Repository libgit2/libgit2, pull requests merged in 2018-04, with the labels that each got.

#4587 Flag options in describe.h as being optional
  include/git2/describe.h
Labels: documentation

#4613 transports: local: fix assert when fetching into repo with symrefs
  src/transports/local.c
  tests/fetchhead/nonetwork.c
Labels: backport

#4614 attr_file: fix handling of directory patterns with trailing spaces
  src/attr_file.c
  src/ignore.c
  tests/attr/ignore.c
Labels: backport

#4596 transports: ssh: disconnect session before freeing it
  src/transports/ssh.c
Labels: backport

#4514 Typedef git_pkt_type and clarify recv_pkt return type
  src/transports/smart.h
  src/transports/smart_protocol.c
Labels: feedback provided

#4522 Submodules-API should report .gitmodules parse errors instead of ignoring them
  src/submodule.c
  tests/submodule/lookup.c
Labels: feedback provided

#4631 fixed stack smashing due to wrong size of struct stat on the stack
  tests/CMakeLists.txt
Labels: backport

#4577 worktree: Read worktree specific reflog for HEAD
  src/refdb_fs.c
  tests/worktree/reflog.c
Labels: backport-0.27.1

#4635 Leak fixes for v0.27.1
  src/remote.c
  src/transports/local.c
  src/worktree.c
Labels: backport-0.27.1
