Repository libgit2/libgit2, pull requests merged in 2018-06, with the labels that each got.

#4530 Fix docurium missing includes
  api.docurium
  include/git2/attr.h
  include/git2/blame.h
  include/git2/branch.h
  include/git2/checkout.h
  include/git2/cherrypick.h
  include/git2/clone.h
  include/git2/describe.h
  include/git2/diff.h
  include/git2/merge.h
  include/git2/proxy.h
  include/git2/rebase.h
  include/git2/remote.h
  include/git2/repository.h
  include/git2/revert.h
  include/git2/stash.h
  include/git2/status.h
  include/git2/submodule.h
  include/git2/sys/index.h
  include/git2/sys/mempack.h
  include/git2/sys/merge.h
  include/git2/transaction.h
  include/git2/types.h
  include/git2/worktree.h
Labels: feedback provided

#4641 Detect duplicated submodules for the same path
  src/submodule.c
  tests/submodule/lookup.c
Labels: backport-0.27.2

#4673 tests: submodule: do not rely on config iteration order
  tests/submodule/lookup.c
Labels: backport-0.27.2

#4558 travis: war on leaks
  .travis.yml
  libgit2_clar.supp
  script/cibuild.sh
  script/cileaks.sh
  script/citest.sh
Labels: feedback provided

#4606 revwalk: avoid walking the entire history when output is unsorted
  src/revwalk.c
  src/revwalk.h
Labels: feedback provided

#4411 Config parser cleanups
  src/config_file.c
  src/config_parse.c
  src/config_parse.h
Labels: bloomberg

#4519 refspec: add public parsing api
  include/git2/refspec.h
  src/refspec.c
  tests/network/refspecs.c
Labels: feedback provided
