Repository libgit2/libgit2, pull requests merged in 2018-03, with the labels that each got.

#4541 CHANGELOG: mention the change to `git_odb_open_rstream`
  CHANGELOG.md
Labels: next release

#4544 pathspec: improve git_pathspec_flag_t doc rendering
  include/git2/pathspec.h
Labels: documentation

#4602 odb: mempack: fix leaking objects when freeing mempacks
  src/odb_mempack.c
Labels: backport
