Repository libgit2/libgit2, pull requests merged in 2021-09, with the labels that each got.

#6031 Support custom git extensions
  include/git2/common.h
  src/libgit2.c
  src/repository.c
  src/repository.h
  tests/core/opts.c
  tests/repo/extensions.c
  tests/repo/open.c
Labels: feature

#6039 indexer: Avoid one `mmap(2)`/`munmap(2)` pair per `git_indexer_append` call
  src/indexer.c
Labels: bugfix

#6067 filter: use a `git_oid` in filter options, not a pointer
  include/git2/attr.h
  include/git2/blob.h
  include/git2/filter.h
  src/attr.c
  src/attr_file.c
  src/attr_file.h
  src/blob.c
  src/filter.c
  tests/filter/bare.c
Labels: abi-breaking

#6076 oidarray: introduce `git_oidarray_dispose`
  include/git2/deprecated.h
  include/git2/oidarray.h
  src/merge.c
  src/oidarray.c
  tests/revwalk/mergebase.c
Labels: api-deprecation, cleanup
