Repository libgit2/libgit2, pull requests merged in 2022-01, with the labels that each got.

#6165 config: handle empty conditional in includeIf
  src/config_file.c
  tests/config/conditionals.c
Labels: bugfix

#6175 remote: support `http.followRedirects` (`false` and `initial`) and follow initial redirects by default
  ci/test.sh
  docs/api-stability.md
  include/git2/remote.h
  include/git2/sys/transport.h
  src/fetch.c
  src/fetch.h
  src/net.c
  src/net.h
  src/proxy.c
  src/proxy.h
  src/push.c
  src/push.h
  src/remote.c
  src/remote.h
  src/transports/http.c
  src/transports/local.c
  src/transports/smart.c
  src/transports/smart.h
  src/transports/smart_protocol.c
  src/transports/ssh.c
  src/transports/winhttp.c
  tests/network/url/redirect.c
  tests/online/clone.c
  tests/online/fetch.c
Labels: feature, git compatibility

#6167 Support scp style paths with ports
  ci/test.sh
  src/common.h
  src/net.c
  src/net.h
  src/transports/ssh.c
  tests/fetchhead/fetchhead_data.h
  tests/fetchhead/nonetwork.c
  tests/network/url/scp.c
  tests/network/url/valid.c
  tests/online/fetch.c
  tests/online/fetchhead.c
  tests/online/remotes.c
Labels: feature, git compatibility

#6168 Improve documentation
  include/git2/apply.h
  include/git2/attr.h
  include/git2/blame.h
  include/git2/blob.h
  include/git2/branch.h
  include/git2/commit.h
  include/git2/common.h
  include/git2/config.h
  include/git2/credential.h
  include/git2/credential_helpers.h
  include/git2/describe.h
  include/git2/diff.h
  include/git2/filter.h
  include/git2/graph.h
  include/git2/ignore.h
  include/git2/index.h
  include/git2/indexer.h
  include/git2/merge.h
  include/git2/message.h
  include/git2/object.h
  include/git2/odb.h
  include/git2/pack.h
  include/git2/patch.h
  include/git2/rebase.h
  include/git2/refdb.h
  include/git2/remote.h
  include/git2/repository.h
  include/git2/revwalk.h
  include/git2/submodule.h
  include/git2/tag.h
  include/git2/tree.h
  include/git2/worktree.h
Labels: documentation

#6138 refs: Speed up packed lookups.
  docs/changelog.md
  src/refdb_fs.c
  tests/refs/crashes.c
  tests/resources/peeled.git/packed-refs
  tests/resources/testrepo.git/packed-refs
  tests/resources/testrepo/.gitted/packed-refs
  tests/resources/testrepo2/.gitted/packed-refs
Labels: v1.4.0
