Repository libgit2/libgit2, pull requests merged in 2022-02, with the labels that each got.

#6195 merge: support zdiff3 conflict styles
  include/git2/checkout.h
  include/git2/merge.h
  src/CMakeLists.txt
  src/blame_git.c
  src/checkout.c
  src/diff_xdiff.c
  src/merge_file.c
  src/patch_generate.c
  src/patch_generate.h
  src/xdiff/git-xdiff.h
  src/xdiff/xdiff.h
  src/xdiff/xdiffi.c
  src/xdiff/xemit.c
  src/xdiff/xhistogram.c
  src/xdiff/xinclude.h
  src/xdiff/xmerge.c
  src/xdiff/xpatience.c
  src/xdiff/xprepare.c
  src/xdiff/xutils.c
  tests/merge/conflict_data.h
  tests/merge/files.c
  tests/merge/workdir/simple.c
Labels: v1.4.0

#6197 merge: comment conflicts lines in MERGE_MSG
  src/merge.c
  tests/cherrypick/workdir.c
  tests/merge/workdir/simple.c
  tests/revert/workdir.c
Labels: v1.4.0

#6196 revparse: support bare '@'
  src/revparse.c
  tests/refs/revparse.c
Labels: v1.4.0

#6192 SHA256: early preparation
  examples/index-pack.c
  fuzzers/packfile_fuzzer.c
  include/git2/index.h
  include/git2/indexer.h
  include/git2/pack.h
  src/branch.c
  src/commit_graph.c
  src/commit_graph.h
  src/config_file.c
  src/hash.c
  src/hash.h
  src/index.c
  src/index.h
  src/indexer.c
  src/midx.c
  src/midx.h
  src/pack-objects.c
  src/pack-objects.h
  src/reset.c
  tests/checkout/crlf.c
  tests/diff/workdir.c
  tests/graph/commitgraph.c
  tests/pack/indexer.c
  tests/pack/packbuilder.c
Labels: v1.4.0

#6206 odb: check for write failures
  src/odb.c
Labels: v1.4.0

#6205 push: Prepare pack before sending pack header.
  src/pack-objects.c
  src/pack-objects.h
  src/transports/smart_protocol.c
Labels: v1.4.0

#6203 Fetch by object id
  include/git2/sys/remote.h
  include/git2/sys/transport.h
  src/fetch.c
  src/oid.h
  src/remote.c
  src/remote.h
  src/transports/local.c
  src/transports/smart.c
  src/transports/smart.h
  src/transports/smart_protocol.c
  tests/core/oid.c
  tests/fetch/local.c
  tests/online/fetch.c
Labels: abi breaking, v1.4.0

#6207 mktmp: improve our temp file creation
  COPYING
  src/CMakeLists.txt
  src/features.h.in
  src/fs_path.c
  src/futils.c
  src/futils.h
  src/libgit2.c
  src/posix.h
  src/rand.c
  src/rand.h
  src/str.c
  src/str.h
  src/unix/posix.h
  src/win32/posix.h
  src/win32/posix_w32.c
Labels: v1.4.0

#6208 diff_file: fix crash if size of diffed file changes in workdir
  include/git2/diff.h
  src/diff_file.c
  src/diff_generate.c
  src/diff_generate.h
  src/diff_tform.c
  src/odb.c
  src/oid.c
  src/oid.h
  tests/diff/externalmodifications.c
Labels: v1.4.0

#6204 merge: fix overlap between GIT_MERGE_FILE_FAVOR__CONFLICTED and GIT_MERGE_FILE_SIMPLIFY_ALNUM
  include/git2/merge.h
  src/merge.c
  src/merge.h
  src/merge_driver.c
Labels: v1.4.0

#6228 win32: `find_system_dirs` does not return `GIT_ENOTFOUND`
  src/win32/findfile.c
  tests/win32/systemdir.c
Labels: bug, v1.4
