Repository libgit2/libgit2, pull requests merged in 2023-08, with the labels that each got.

#6615 config: provide an "origin" for config entries
  fuzzers/config_file_fuzzer.c
  include/git2/config.h
  include/git2/sys/config.h
  src/libgit2/config_backend.h
  src/libgit2/config_entries.c
  src/libgit2/config_entries.h
  src/libgit2/config_file.c
  src/libgit2/config_list.c
  src/libgit2/config_list.h
  src/libgit2/config_mem.c
  src/libgit2/config_snapshot.c
  src/util/strlist.c
  src/util/strlist.h
  tests/libgit2/config/memory.c
  tests/libgit2/config/read.c
  tests/libgit2/config/snapshot.c
Labels: abi breaking

#6626 cmake: fix openssl build on win32
  cmake/SelectHTTPSBackend.cmake
  src/CMakeLists.txt
Labels: v1.7

#6628 ci: retry flaky online tests
  ci/test.sh
Labels: build

#6629 ci: update to macOS 12
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  ci/test.sh
Labels: build
