Repository libgit2/libgit2, pull requests merged in 2024-10, with the labels that each got.

#6898 push: handle tags to blobs
  src/libgit2/push.c
  tests/libgit2/network/remote/tag.c
Labels: bug

#6908 README updates
  README.md
Labels: documentation

#6037 checkout: make safe checkout the default
  include/git2/checkout.h
  include/git2/clone.h
  include/git2/rebase.h
  include/git2/stash.h
  include/git2/submodule.h
  src/libgit2/apply.c
  src/libgit2/checkout.c
  src/libgit2/checkout.h
  src/libgit2/cherrypick.c
  src/libgit2/clone.c
  src/libgit2/clone.h
  src/libgit2/merge.c
  src/libgit2/revert.c
  tests/libgit2/checkout/binaryunicode.c
  tests/libgit2/checkout/conflict.c
  tests/libgit2/checkout/head.c
  tests/libgit2/checkout/icase.c
  tests/libgit2/checkout/index.c
  tests/libgit2/checkout/tree.c
  tests/libgit2/cherrypick/workdir.c
  tests/libgit2/clone/local.c
  tests/libgit2/clone/nonetwork.c
  tests/libgit2/merge/workdir/dirty.c
  tests/libgit2/merge/workdir/renames.c
  tests/libgit2/merge/workdir/simple.c
  tests/libgit2/online/clone.c
  tests/libgit2/online/fetchhead.c
  tests/libgit2/perf/helper__perf__do_merge.c
  tests/libgit2/revert/workdir.c
Labels: abi breaking, v.next

#6559 remote: add update_refs with git_refspec
  examples/fetch.c
  include/git2/remote.h
  src/libgit2/push.c
  src/libgit2/remote.c
  tests/libgit2/network/fetchlocal.c
  tests/libgit2/online/clone.c
  tests/libgit2/online/fetch.c
  tests/libgit2/online/push_util.c
  tests/libgit2/online/push_util.h
  tests/libgit2/submodule/update.c
Labels: feature, abi breaking, v.next

#6915 cmake: update python locator
  tests/libgit2/CMakeLists.txt
  tests/util/CMakeLists.txt
Labels: build, v.next

#6914 cmake-standard c standards
  .github/workflows/main.yml
  CMakeLists.txt
  README.md
  cmake/SetCStandard.cmake
  deps/llhttp/api.c
  deps/ntlmclient/CMakeLists.txt
  examples/CMakeLists.txt
  fuzzers/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/libgit2/CMakeLists.txt
  src/util/CMakeLists.txt
  tests/headertest/CMakeLists.txt
  tests/libgit2/CMakeLists.txt
  tests/util/CMakeLists.txt
Labels: build, v.next

#6906 Add OpenSSL-FIPS option to USE_SHA256 CMake flag
  .github/workflows/nightly.yml
  cmake/SelectHashes.cmake
  src/libgit2/commit_graph.c
  src/libgit2/midx.c
  src/util/CMakeLists.txt
  src/util/git2_features.h.in
  src/util/hash/openssl.c
  src/util/hash/openssl.h
  src/util/hash/sha.h
Labels: feature, v.next
