Repository libgit2/libgit2, pull requests merged in 2024-02, with the labels that each got.

#6439 Implement push options on push
  ci/test.sh
  include/git2/remote.h
  include/git2/sys/remote.h
  src/libgit2/push.c
  src/libgit2/push.h
  src/libgit2/remote.c
  src/libgit2/transports/smart.c
  src/libgit2/transports/smart.h
  src/libgit2/transports/smart_protocol.c
  tests/libgit2/online/push.c
  tests/resources/pushoptions.git/HEAD
  tests/resources/pushoptions.git/branches/.gitignore
  tests/resources/pushoptions.git/config
  tests/resources/pushoptions.git/description
  tests/resources/pushoptions.git/hooks/pre-receive
  tests/resources/pushoptions.git/info/exclude
  tests/resources/pushoptions.git/objects/info/.gitignore
  tests/resources/pushoptions.git/objects/pack/.gitignore
  tests/resources/pushoptions.git/refs/heads/.gitignore
  tests/resources/pushoptions.git/refs/tags/.gitignore
Labels: feature, v1.8

#6740 meta: add dependency tag to release.yml
  .github/release.yml
Labels: build

#6742 revparse: ensure bare '@' is truly bare
  src/libgit2/revparse.c
  tests/libgit2/refs/revparse.c
Labels: bug, v1.8

#6743 repo: ensure we can initialize win32 paths
  src/libgit2/repository.c
  tests/libgit2/repo/init.c
Labels: bug

#6240 Swap `GIT_DIFF_LINE_(ADD|DEL)_EOFNL` to match other Diffs
  src/libgit2/patch_parse.c
  tests/libgit2/diff/parse.c
Labels: bug, v1.8

#6744 http: support empty http.proxy config setting
  src/libgit2/transports/http.c
  src/libgit2/transports/winhttp.c
  tests/libgit2/online/fetch.c
Labels: bug

#6739 More `safe.directory` improvements
  src/libgit2/repository.c
  src/util/fs_path.c
  src/util/fs_path.h
  src/util/win32/posix_w32.c
  tests/clar/clar/sandbox.h
  tests/libgit2/repo/open.c
  tests/util/path.c
  tests/util/path/core.c
  tests/util/path/win32.c
Labels: bug, git compatibility, v1.8

#5893 Ensure that completely ignored diff is empty
  src/libgit2/diff_print.c
  tests/libgit2/diff/workdir.c
Labels: up for grabs
